# Generated by Django 5.1.2 on 2024-11-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='username',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
